name: ordersanalysis
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  fl_chart: ^0.69.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  shared_preferences: ^2.3.4
  easy_localization: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0




flutter:

  uses-material-design: true

  assets:
    - assets/orders-json.json
    - assets/lang/

